required: sudo
language: generic
services:
  - docker

before_install:
  - docker build -t udioz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run udioz/react-test npm test -- --coverage

after_success:
  - docker build -t udioz/multi-client ./client
  - docker build -t udioz/multi-nginx ./nginx
  - docker build -t udioz/multi-server ./server
  - docker build -t udioz/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push udioz/multi-client
  - docker push udioz/multi-nginx
  - docker push udioz/multi-server
  - docker push udioz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-765488972592"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"